### ISSUE TITLE
[Request] Checked as default

### ISSUE THREAD

**Issue by tmdevde** [thany/gdpr-cookie#2]
First of all thank you so much for this awesome Plugin. It's perfectly working. The only thing i would wish for is an option the set a cookie option checked as default but not disabled.

**Comment by thany** [comment]
Hey thanks for using it 😀

As far as I understand the GDPR, it's not allowed to have options checked by default. This would defeat the purpose of the user giving express consent. But maybe I'm misiing something. Do you have a use case to convince me?

**Comment by isev-general** [comment]
Hi @thany,

Thanks for making this great plugin. I also have this issue. I've looked into it and from what I can see, if the category does not deal with personally identifiable information it can be checked by default.

>The cookies are grouped into four comprehensive categories, that the user may check or uncheck. Necessary cookies cannot be unchecked, because they are whitelisted and are necessary for the website to function properly. **Cookie categories that don’t handle personal data may be pre-checked, whereas those that do, must be actively opted into by the user to be compliant.**
From https://www.cookiebot.com/en/gdpr-cookies/

If this is the case I think having default checked should be an option but disabled by default.

**Comment by tmdevde** [comment]
Ah yes i searched for that. Most of the sides i see, wich are using GDPR Cookie Scripts, have prechecked fields for alle their cookies.

**Comment by thany** [comment]
The way I understand the law (and I am by no means a lawyer, and I'm not able to read legalese) cookie categories that don't handle personal data don't need to be displayed at all. It's more like common courtesey to display them to visitors.

You can also rename "Essential" to something like "Essential & anonymous tracking", which is also allowed, afaik.

If I'm going to include default checked categories, I'm not sure if true consent is given when the visitor accepts them. Otoh, if it's allowed and liability lies with the site owner (which it does), why do I even care? 😄

**Comment by thany** [comment]
We actually got this request from a customer now, so I have no choice. I don't fully agree, because it's a grey area. But we couldn't talk the customer out of it. Oh well :)

Thanks for the PR!
